# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b155e2b5bf3be7447ba78dd58a2d6086f0c3b179cae4da90541bbb9be3719a5327c332155cd9e4e8319ca169fa4919918070693444bc037a282472f38fb57bc2

test:
  secret_key_base: f3540450f121850b3427008fc5aeca73f73f09a90a50459009dd1b805acd1f97f801ee653b75ecf543e584cc894d3b3581221bdde00ab651eb007fb846d746c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
